# Generated by Django 5.1.5 on 2025-01-30 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_posts_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='banner',
            field=models.ImageField(blank=True, default='fallback.png', upload_to=''),
        ),
    ]
